apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
  namespace: monitoring
data:
  config.yaml: |
    receivers:
      jmx:
        jar_path: /etc/otel/jmx-metrics.jar
        target_system: kafka

    exporters:
      prometheus:
        endpoint: "0.0.0.0:9464"

    service:
      pipelines:
        metrics:
          receivers: [jmx]
          exporters: [prometheus]
