apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-xffm-sql-pvc
  namespace: mysql-xffm-nm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: mysql-xffm-sql-scn
