apiVersion: v1
kind: Service
metadata:
  namespace: mysql-xffm-nm
  name: mysql-xffm-sql-service-internal
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: mysql-xffm-sql-depl-managed-pods