apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: mysql-xffm-nm
  name: mysql-xffm-sql-persistent-volume
  labels:
    type: mysql-xffm-sql-label
spec:
  storageClassName: mysql-xffm-sql-scn
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/lkd/srv/mnt/mysql-xffm-pv-storage"
