apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-xff-sts
  namespace: kafka-xff-nm
spec:
  serviceName: "kafka-xff-headless-service"
  replicas: 1
  selector:
    matchLabels:
      app: kafka-xff-app
  template:
    metadata:
      labels:
        app: kafka-xff-app
    spec:
      containers:
        - name: kafka-xff-container
          image: apache/kafka:latest
          ports:
            - containerPort: 9092
              name: internal
            - containerPort: 9093
              name: controller
            - containerPort: 9094
              name: external
          volumeMounts:
            - name: kafka-xff-pvc-provided-volume
              mountPath: /var/lib/kafka-xff-log-dirs
          env:
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: CLUSTER_ID
              value: "5L6g3nShT-eMCtK--X86sw"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
            - name: KAFKA_LISTENERS
              value: "INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka-xff-sts-0.kafka-xff-headless-service.kafka-xff-nm.svc.cluster.local:9092,EXTERNAL://192.168.55.103:30092"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@kafka-xff-sts-0.kafka-xff-headless-service.kafka-xff-nm.svc.cluster.local:9093"
            - name: KAFKA_LOG_DIRS
              value: "/var/lib/kafka-xff-log-dirs/data"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_JMX_PORT
              value: "9999"
            - name: KAFKA_JMX_OPTS
              value: "-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1"
      volumes:
        - name: kafka-xff-pvc-provided-volume
          persistentVolumeClaim:
            claimName: kafka-xff-pvc
