apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-xff-sts
  namespace: kafka-xff-nm
spec:
  serviceName: "kafka-xff-sts-sn"
  replicas: 1
  selector:
    matchLabels:
      app: kafka-xff-app
  template:
    metadata:
      labels:
        app: kafka-xff-app
    spec:
      containers:
        - name: kafka-xff-container
          image: apache/kafka:latest
          ports:
            - containerPort: 9092
              name: kafka-xffp
            - containerPort: 9093
              name: controller-xffp
            #- containerPort: 9094
            #  name: p-xff-external
          volumeMounts:

            - name: kafka-xff-pvc-provided-volume
              mountPath: /var/lib/kafka-xff-log-dirs

          env:

            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"

            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"

            - name: KAFKA_LISTENERS
              value: "INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094"
              #value: "INTERNAL://:9092,EXTERNAL://:9094"

            - name: KAFKA_NODE_ID
              value: "1"

            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
              #value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"

            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"

            - name: CLUSTER_ID
              value: "5L6g3nShT-eMCtK--X86sw"

            - name: KAFKA_ADVERTISED_LISTENERS              
              
              #value: "PLAINTEXT://192.168.55.103:9092"
              value: "INTERNAL://kafka-xff-headless-service.kafka-xff-nm.svc.cluster.local:9092,EXTERNAL://192.168.55.103:30092,CONTROLLER://192.168.55.103:9093"

              #value: "PLAINTEXT://10.1.34.157:9092"
              #value: "INTERNAL://kafka-xff-headless-service.kafka-xff-nm.svc.cluster.local:9092,EXTERNAL://192.168.55.103:9092"
              #value: "PLAINTEXT://kafka-xff-headless-service.kafka-xff-nm.svc.cluster.local:9092"
              #value: "PLAINTEXT://kafka-xff-sts-0.kafka-xff-headless-service.kafka-xff-nm.svc.cluster.local:9092"              


            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              #value: "1@kafka-xff-sts-0.kafka-xff-headless-service.kafka-xff-nm.svc.cluster.local:9093"
              value: "1@kafka-xff-headless-service.kafka-xff-nm.svc.cluster.local:9093"

            - name: KAFKA_LOG_DIRS
              value: "/var/lib/kafka-xff-log-dirs/data"

            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"

            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"

            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
              
      volumes:
        - name: kafka-xff-pvc-provided-volume
          persistentVolumeClaim:
            claimName: kafka-xff-pvc