apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: kafka-xff-nm
  name: kafka-xff-pv-storage
  labels:
    type: kafka-xff-app
spec:
  storageClassName: kafka-xff-scn
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/lkd/srv/mnt/kafka-xff-pv-storage"
