apiVersion: v1
data:
  config: |
    address-pools:
    - name: my-pool
      protocol: layer2
      addresses:
      - 192.168.55.100-192.168.55.300
      - 192.168.55.400-192.168.55.600
      - 192.168.55.700-192.168.55.800
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config":"address-pools:\n- name: my-pool\n  protocol: layer2\n  addresses:\n  - 192.168.55.100-192.168.55.300\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"config","namespace":"metallb-system"}}
  creationTimestamp: "2025-03-01T23:20:53Z"
  name: config
  namespace: metallb-system
  resourceVersion: "11040113"
  uid: 66a4f101-fd3f-4a6e-a116-6b34bbb6e02a
