apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-xff-pvc
  namespace: kafka-xff-nm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: kafka-xff-scn