apiVersion: v1
kind: Service
metadata:
  name: kafdrop-xffk-apps-kafdrop-load-balancer
  namespace: kafdrop-xffk-nm
spec:
  selector:
    app: kafdrop-xffk-apps-kafdrop-depl-managed-pods
  ports:
    - protocol: TCP
      port: 9052
      targetPort: 9000
  type: LoadBalancer
